import React, { useEffect, useState } from 'react';
import {
  Alert,
  AlertIcon,
  Badge,
  Box,
  Button,
  Code,
  HStack,
  List,
  ListItem,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Spinner,
  Text,
} from '@chakra-ui/react';
import lmApi from '../api/lmApi';
import RichText from './RichText';
import { formatAnswerValue } from '../format';

/**
 * Sample papers for a whole tutorial or assignment, end to end.
 *
 * Serves tutorials and assignments alike — the papers are generated by the same
 * engine, so one component reads both rather than two drifting copies.
 *
 * It used to sit at the bottom of the editor, which was the wrong place: the
 * editor's question is "is this question right", answered by the preview under
 * each question, while "what does the finished paper look like" is a question
 * about the whole thing and belongs where it is listed.
 *
 * Always runs against the *saved* version — that is what generation reads,
 * and there is nothing unsaved here to disagree with it.
 */
export default function PaperPreviewModal({ isOpen, onClose, classId, kind = 'tutorial', item }) {
  const [samples, setSamples] = useState(null);
  const [warnings, setWarnings] = useState([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const run = async () => {
    setBusy(true);
    setError(null);
    try {
      const result =
        kind === 'assignment'
          ? await lmApi.previewAssignment(classId, item._id, 3)
          : await lmApi.previewTutorial(classId, item._id, 3);
      setSamples(result.samples);
      setWarnings(result.warnings || []);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  };

  // Rolls on open, so the modal is never a button that does nothing yet.
  useEffect(() => {
    if (!isOpen || !item?._id) return;
    setSamples(null);
    run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, item?._id]);

  return (
    <Modal isOpen={isOpen} onClose={onClose} size="3xl" scrollBehavior="inside">
      <ModalOverlay />
      <ModalContent>
        <ModalHeader>
          Preview — {item?.title}
          <Text fontSize="sm" fontWeight="400" color="lmFg.muted">
            The actual numbers three students would be given.
          </Text>
        </ModalHeader>
        <ModalCloseButton />
        <ModalBody>
          {error && (
            <Alert status="error" borderRadius="md" mb={3} fontSize="sm">
              <AlertIcon />
              {error}
            </Alert>
          )}

          {warnings.length > 0 && (
            <Alert status="warning" borderRadius="md" mb={3} fontSize="sm" alignItems="flex-start">
              <AlertIcon />
              <Box>
                <Text fontWeight="600">Some draws produce an unanswerable question:</Text>
                <List fontSize="xs" mt={1}>
                  {warnings.map((warning) => (
                    <ListItem key={warning}>• {warning}</ListItem>
                  ))}
                </List>
              </Box>
            </Alert>
          )}

          {busy && !samples ? (
            <HStack py={6} justify="center">
              <Spinner size="sm" />
              <Text fontSize="sm" color="lmFg.muted">
                Rolling sample papers…
              </Text>
            </HStack>
          ) : (
            (samples || []).map((sample) => (
              <Box key={sample.label} mb={4} borderWidth="1px" borderColor="lmBorder.base" borderRadius="md" p={3}>
                <Badge mb={2}>{sample.label}</Badge>
                {sample.questions.map((question, index) => (
                  <Box key={index} mb={3}>
                    <RichText>{question.prompt}</RichText>
                    <HStack fontSize="xs" color="lmFg.muted" mt={1} wrap="wrap">
                      {Object.entries(question.values || {}).map(([name, value]) => (
                        <Code key={name} fontSize="xs">
                          {name} = {String(value)}
                        </Code>
                      ))}
                    </HStack>
                    <HStack fontSize="xs" mt={1} wrap="wrap">
                      {(question.expected || [])
                        .filter((expected) => (expected.partIndex ?? null) === null)
                        .map((expected) => (
                          <Badge key={expected.key} colorScheme={expected.error ? 'red' : 'green'}>
                            {expected.label}:{' '}
                            {expected.error
                              ? 'failed'
                              : `${formatAnswerValue(expected.value, expected.decimals)} ${expected.unit}`}
                          </Badge>
                        ))}
                    </HStack>

                    {(question.parts || []).map((part, partIndex) => (
                      <Box key={partIndex} mt={2} pl={3} borderLeftWidth="2px" borderColor="lmHue.purple200">
                        {part.label && (
                          <Text fontSize="sm" fontWeight="700" color="lmHue.purple700">
                            {part.label}
                          </Text>
                        )}
                        <RichText fontSize="sm">{part.prompt}</RichText>
                        <HStack fontSize="xs" mt={1} wrap="wrap">
                          {(question.expected || [])
                            .filter((expected) => expected.partIndex === partIndex)
                            .map((expected) => (
                              <Badge key={expected.key} colorScheme={expected.error ? 'red' : 'green'}>
                                {expected.label}:{' '}
                                {expected.error
                                  ? 'failed'
                                  : `${formatAnswerValue(expected.value, expected.decimals)} ${expected.unit}`}
                              </Badge>
                            ))}
                        </HStack>
                      </Box>
                    ))}
                  </Box>
                ))}
              </Box>
            ))
          )}
        </ModalBody>
        <ModalFooter gap={2}>
          <Button size="sm" variant="outline" onClick={run} isLoading={busy}>
            Roll again
          </Button>
          <Button size="sm" onClick={onClose}>
            Close
          </Button>
        </ModalFooter>
      </ModalContent>
    </Modal>
  );
}
